### ISSUE TITLE
'onChange' event

### ISSUE THREAD

**Issue by yak-i** [wix/react-native-zss-rich-text-editor#1]
Is there something like 'onChange' event of content?

**Comment by xxllexx** [comment]
@yak-i now you can do the next: 
`<RichTextEditor enableOnChange={ true } ref={(r) => this.richText = r}/>`
and then: 
`this.richText.registerContentChangeListener((text) => { ... })`

**Comment by razvan-tudosa** [comment]
It would be nice to have this documented.
