### ISSUE TITLE
Are there any ways to disable editing?

### ISSUE THREAD

**Issue by shaoting0730** [wix/react-native-zss-rich-text-editor#105]
Are there any ways to disable editing?

Are there any ways to disable editing?

Are there any ways to disable editing?

**Comment by SurfeeS** [comment]
Did u find out plz?

**Comment by shaoting0730** [comment]
no,i use   https://github.com/archriss/react-native-render-html

**Comment by ThangLuuQuoc** [comment]
> Are there any ways to disable editing?
> 
> Are there any ways to disable editing?
> 
> Are there any ways to disable editing?

View this ticket : https://github.com/wix/react-native-zss-rich-text-editor/issues/24
