### ISSUE TITLE
Does not compile under React Native version 0.40.0

### ISSUE THREAD

**Issue by cherniv** [wix/react-native-zss-rich-text-editor#11]
Perhaps related to React Native' last breaking change: 

https://github.com/alinz/react-native-webview-bridge/issues/199

https://github.com/facebook/react-native/releases/tag/v0.40.0

**Comment by tendolukwago** [comment]
Also having this problem...

**Comment by tendolukwago** [comment]
@cherniv updating the imports prefixed with RCT in the RCTWebViewBridge.m file and the RCTWebViewBridgeManager.m files in the underlying react-native-web-view-bridge-updated project did the trick for me.  For example, instead of  #import "RCTLog.h",  use #import <React/RCTLog.h>
