### ISSUE TITLE
How to remove the title?

### ISSUE THREAD

**Issue by powercoder23** [wix/react-native-zss-rich-text-editor#12]
Hi,

I have a requirement where i just need the  editor not the title, is there a way to get rid of the title?

Thanks,
Dhiraj

**Comment by artald** [comment]
Yes, it's possible. Set the `hiddenTitle` prop to hide the title.

**Comment by powercoder23** [comment]
Hi @artald,

Thank you for the help, Cheers!

Now, the file i have `RichTextEditor.js` in my node_modules is different from what i see in github (your repository), when i am doing `npm install react-native-zss-rich-text-editor` i am getting `react-native-zss-rich-text-editor@1.0.0`, i guess i am not getting the updated file.

Can you please help getting the latest file?

Thanks,
Dhiraj

**Comment by artald** [comment]
I think we didn't publish a version for a while now since we've been using an internal temp version while adding features.

@yedidyak can you please pull and publish? it seems that I don't have credentials for the public npm.

**Comment by razvan-tudosa** [comment]
I also need this feature. Could you please update the package?

**Comment by artald** [comment]
new version is published: `1.0.2`
