### ISSUE TITLE
Editor does not get focused android. 

### ISSUE THREAD

**Issue by saurabhabh** [wix/react-native-zss-rich-text-editor#138]
Hi , 
I have created an app and used this editor(version 1.1.0), react-native version "0.55.4" . The editor works fine on the android emulator. But when I install it on my testing device Motorola G5 Plus and try to focus the editor by clicking on it, the editor does not get focused. 
Note: I tested it on Xiaomi Note 5 pro phone and it works fine on this device too. 
I am unable to think as to what the issue be.  Please help . !!

**Comment by saurabhabh** [comment]
Sorry I just came across a similar issue. [Cant focus on Andorid #108 ](https://github.com/wix/react-native-zss-rich-text-editor/issues/108#issue-329959344) Please add this to the same.

**Comment by saurabhabh** [comment]
Fixed it by making changes to my styles.

**Comment by sahil6111** [comment]
@saurabhabh Can you please give an example which styles you have changed?
Because in my case in android the editor is focused but some white overlay is above the text i type.

**Comment by saurabhabh** [comment]
@sahil6111  This is how I am using it. If I remember correctly it was some issue with the flexdirection. 
![image](https://user-images.githubusercontent.com/8706481/48994139-a19ac380-f167-11e8-9ec8-6a960ee27c79.png)
![image](https://user-images.githubusercontent.com/8706481/48994164-c5f6a000-f167-11e8-8d1c-4766eb7ecefd.png)
![image](https://user-images.githubusercontent.com/8706481/48994180-d9a20680-f167-11e8-8d24-b7fb3e185d73.png)

**Comment by sahil6111** [comment]
@saurabhabh Thanks for the response, i will try to look into it.
