### ISSUE TITLE
Place cursor at end of initial content

### ISSUE THREAD

**Issue by mtr1012** [wix/react-native-zss-rich-text-editor#147]
I am using react-native-zss-rich-text-editor to display and edit HTML content.
I am using focusContent() function to focus on the content field.
My problem is the cursor always place at start of initial content:
[https://www.youtube.com/watch?v=gVLfUXxpwWM](url)
I want the cursor place at end of initial content.
Anyone please help
Many thanks

**Comment by TharaViswa** [comment]
Have you find any solution?

**Comment by mtr1012** [comment]
> Have you find any solution?

https://github.com/mtr1012/react-native-zss-rich-text-editor/commit/3f77680133463d1e0c21b5402806d7bba6b03179

here it is, i've fixed it
