### ISSUE TITLE
FAILURE: Build failed with an exception

### ISSUE THREAD

**Issue by nhuthan** [wix/react-native-zss-rich-text-editor#16]
I got this error when i build release app
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeReleaseResources'.
> C:\Projects\ReactNative\ABC\android\app\src\main\res\drawable-mdpi\node_modules_reactn
ativezssrichtexteditor_src_editor.html: Error: The file name must end with .xml or .png
```

**Comment by yedidyak** [comment]
Hi, this happens if you have manually run assembleReleaseResources. To fix this simply delete the file 
`C:\Projects\ReactNative\ABC\android\app\src\main\res\drawable-mdpi\node_modules_reactn
ativezssrichtexteditor_src_editor.htm`
