### ISSUE TITLE
Maintain rich text controls, find partners

### ISSUE THREAD

**Issue by liukefu2050** [wix/react-native-zss-rich-text-editor#190]
I have a real project that needs rich text controls, so I have to use this project, and I can't find a replacement. So I copied two projects https://github.com/shijingsh/react-native-webview-bridge-updated And https://github.com/shijingsh/react-native-editor

But the ability of discovery is limited. Look for the same partners as me to maintain this project together

**Comment by alfarodarwaynejay** [comment]
I'm new to RN but I'd like to help.

**Comment by liukefu2050** [comment]
see https://github.com/wxik/react-native-rich-editor
