### ISSUE TITLE
How to insert a  Image?

### ISSUE THREAD

**Issue by ouyangdxq** [wix/react-native-zss-rich-text-editor#2]
How to insert a  Image?

**Comment by ouyangdxq** [comment]
insertImage,yeah,more demo will be better

**Comment by yedidyak** [comment]
`this.richText.insertImage({src: '*URL_OF_IMAGE*'});`

**Comment by cinder92** [comment]
@yedidyak  it need to be an absolute path (file from phone) ? or it needs to be a URL image?

**Comment by yedidyak** [comment]
It should be a URL. A local path may also work, but is not guaranteed.

**Comment by cinder92** [comment]
@yedidyak  thanks, i'll try

**Comment by cizhaoyang** [comment]
@cinder92 How do you insert images and success? Can you give me codes? When i insert images, it can not show.
