### ISSUE TITLE
Adding images

### ISSUE THREAD

**Issue by gbenga504** [wix/react-native-zss-rich-text-editor#23]
Do I add images to the editor using the image react native tag or do I just need to supply the data uri

**Comment by gbenga504** [comment]
Fixed it already,  the src,  width and height with any other attributes exposed to the normal image element of html has to be sent in the insertImage method as an object...  E. G insertImage({src: dataURI,  width:20, height:20 })

**Comment by ignivahermenpreet** [comment]
gbenga504  Please share your code or any demo where you implement this method. Thank you in advance.

**Comment by kantharia** [comment]
Hi, @gbenga504 what are the attributes we can pass?
