### ISSUE TITLE
problem with bullets/lists

### ISSUE THREAD

**Issue by Shujito** [wix/react-native-zss-rich-text-editor#40]
If there's only one item and it gets deleted, the cursor disappears and can't be focused again if you touch the editor

[I recorded it so you can understand better what is happening](https://github.com/wix/react-native-zss-rich-text-editor/files/1142686/editor-woes-1.zip)

I noticed that, you can still edit if you don't touch the editor. If you add a new line and delete it, the cursor comes back and you can touch the editor without losing the focus

[I also recorded when that happens](https://github.com/wix/react-native-zss-rich-text-editor/files/1142701/editor-woes-2.zip)

Maybe there's a way to disable touch or focus?

**Comment by vonovak** [comment]
it seems that all of what you recorded happened on an emulator, did you test with a device?

**Comment by Shujito** [comment]
I didn't

Later I used the placeholder, that fixed it, the focus doesn't disappear anymore

**Comment by JohnHour89** [comment]
hi, can you share the code of how you use the placeholder? because i use the HTML it doesn't show any title or content and toolbar actions also does not work. Please advice. Thank you

**Comment by Shujito** [comment]
like this

	/* ... */
	render() {
	  return (
	    <RichTextEditor
	      contentPlaceholder={'your placeholder is here'}
	      ...otherProps
	    />
	  );
	}
	/* ... */

just add the `contentPlaceholder` prop to the editor component

**Comment by JohnHour89** [comment]
no need to action or something like this:

```
async getHTML() {
    const titleHtml = await this.richtext.getTitleHtml();
    const contentHtml = await this.richtext.getContentHtml();
    alert(titleHtml + ' ' + contentHtml)
  }
```

because I tried your method also does't show any text in the editor...
