### ISSUE TITLE
How to hide/disable the title part of the editor

### ISSUE THREAD

**Issue by Dirk-Kokx** [wix/react-native-zss-rich-text-editor#44]
For my application I don't need the title part of the editor. Is there a way to disable it?

**Comment by Dirk-Kokx** [comment]
The ReadMe isn't very informative on this part, but diving into the code I found you can simply set the prop 'hiddenTitle' to true. Perfect implementation, great work!

**Comment by pdkn** [comment]
Can maintainers kindly add "hiddenTitle" prop to Readme/docs before closing this?
