### ISSUE TITLE
Insert image tapped not working

### ISSUE THREAD

**Issue by bahadircivelek** [wix/react-native-zss-rich-text-editor#55]
Hi,
Thank you for this lib. Everythings work fine but when i click insert image button in toolbar nothing happen, I wonder what the problem could be ?

**Comment by yoginair** [comment]
@bahadircivelek how you resolved this issue

**Comment by bahadircivelek** [comment]
@yoginair i created custom component for this actions. using react-native-image-picker lib.

**Comment by ignivahermenpreet** [comment]
@bahadircivelek how you resolved this issue. I am using this package react-native-image-crop-picker when i click on image icon. Th en add this function
                       <RichTextToolbar
                            actions={[  actions.insertImage,
                                        actions.setBold,
                                        actions.setItalic,
                                        actions.insertBulletsList,
                                        actions.insertOrderedList,
                                        actions.insertLink]}
                            getEditor={() => this.richtext}
                            onPressAddImage={()=>{
                                ImagePicker.openPicker({
                                    width: 300,
                                    height: 300,
                                    cropping: true
                                    }).then(image => {
                                        console.log(image)
                                    }).catch( error => {
                                      console.log('There has been a problem with your fetch operation: ' + error);
                                    })

                            }}
                            iconTint='black'
                            selectedButtonStyle={{backgroundColor:'#51671d'}}
                          />

How i can add the selected image in text editor. please share your code or any demo for this.

**Comment by RobinsonKameron** [comment]
@ignivahermenpreet did you ever figure out how to add images to the editor?
