### ISSUE TITLE
it makes some problem 

### ISSUE THREAD

**Issue by kevinchanyuanhui** [wix/react-native-zss-rich-text-editor#64]
the pickture can't add

**Comment by allyju** [comment]
Try the following：
`          <RichTextToolbar
                    getEditor={() => this.richtext}
                    onPressAddImage={() => {
                        this.richtext.insertImage({
                            "src": "http://img.blog.csdn.net/20170428170152489",
                            "width": "50px",
                            "height": '90px'
                        })
                    }}
                    onPressAddLink={() => {
                        this.richtext.insertLink("http://www.baidu.com", "百度")
                    }}
                />
                `

**Comment by kevinchanyuanhui** [comment]
thanks
