### ISSUE TITLE
iOS error - undefined is not an object (evaluating 'RCTWebViewBridgeManager.NavigationType')

### ISSUE THREAD

**Issue by Monte9** [wix/react-native-zss-rich-text-editor#70]
Got it to work on Android, but I am unable to get this working on iOS. I have followed the installation instructions on the `react-native-webview-bridge` repo [here](https://github.com/alinz/react-native-webview-bridge#installation).

Although I keep seeing the following error. Kindly help. 

<img src="https://user-images.githubusercontent.com/7840686/34656784-a224d4cc-f3d3-11e7-8903-80c69ef3823e.png" width="300" />

Also this repo hasn't been updated for almost 1 year. Are there any better alternatives to get a rich text editor for React Native?

**Comment by zhangquxi** [comment]
+1 same

**Comment by Monte9** [comment]
I fixed it up updated to the latest version. Hope that works for you too! 👍

**Comment by murrayee** [comment]
+1

**Comment by export-mike** [comment]
@Monte9 what version did you update to? I'm on ^1.1.0 and I'm having this issue...

**Comment by mehrapratham** [comment]
@Monte9 what version did you update to ?

**Comment by Monte9** [comment]
`"react-native-zss-rich-text-editor": "^1.1.0",`

**Comment by mehrapratham** [comment]
@Monte9 I also "^1.1.0" version is used but getting this error 
https://user-images.githubusercontent.com/7840686/34656784-a224d4cc-f3d3-11e7-8903-80c69ef3823e.png
any solution ?

**Comment by dongawli** [comment]
+1.. I am still not able to run this on iOs.. Android its working fine. 
Can anyone please post the solution here ?

I've integrated the ZSS richtext editor into existing iOS app and done the steps given for linking the react-native-webview-bridge repository. 

react-native: 0.59.0
react: 16.8.3.

**Comment by mohammad-goldast** [comment]
+1
Please, if anyone have a solution, let us know, how we can run this on IOS...

**Comment by arneson** [comment]
Do you guys have a repo with a reproducable test case for this issue? I can't seem to reproduce it using https://github.com/arneson/react-native-zss-rich-text-editor and https://github.com/alinz/react-native-webview-bridge

Just a small sample project would be enough. @mohammad-goldast  @dongawli

**Comment by arneson** [comment]
I've created a small running example of a successful installation, 
https://github.com/arneson/react-native-zss-rich-text-editor-demo
