### ISSUE TITLE
Warning: RichTextToolbar has a method called componentDidReceiveProps().

### ISSUE THREAD

**Issue by Yandamuri** [wix/react-native-zss-rich-text-editor#79]
I am getting following Warning while using react-native-zss-rich-text-editor.
![screenshot_1518260123](https://user-images.githubusercontent.com/31983789/36061643-e46a46e0-0e82-11e8-9b2e-94bc83d1e685.png)

When I opened RichTextToolbar.js indeed there is  componentDidReceiveProps() method which is causing this warning.

Could anybody let me know how to overcome this warning?

**Comment by Silence-more** [comment]
请问您解决了吗？

**Comment by omnikitty** [comment]
I simply went into node_modules/react-native-zss-rich-text-editor/src/RichTextToolbar.js, found the componentDidReceiveProps() method, and changed the name to componentWillReceiveProps instead. So far works okay for me, will update if I figure out it breaks anything.
